version: '3'

services:
  cache:
    image: 'redis:latest'
    ports:
      - 6379:6379
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping | grep PONG"]
      interval: 1s
      timeout: 3s
      retries: 5
    volumes:
      - cache:/var/lib/redis/data
    profiles:
      - application

  backend:
    build: ./backend
    ports:
      - "8080:8080"
    env_file: .env.docker
    depends_on:
      - cache
    profiles:
      - application

volumes:
  cache: